library:
  source-dirs: src
tests:
  mineSweep-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mineSweep
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- QuickCheck
- hspec
- matrix
- base >= 4.7 && < 5
name: mineSweep
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/mineSweep
license: BSD3
executables:
  mineSweep-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mineSweep
description: Please see the README on GitHub at <https://github.com/githubuser/mineSweep#readme>
